# Generated by Django 5.2.3 on 2025-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlignedId",
            fields=[
                (
                    "aligned_id",
                    models.CharField(
                        help_text="From aligned table. Includes sr-gs, pacbio, nanopore, etc. alignments",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentId",
            fields=[
                (
                    "experiment_id",
                    models.CharField(
                        help_text="From experiments table. Includes sr-gs, pacbio, nanopore, etc. experiments",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalProjectId",
            fields=[
                (
                    "internal_project_id",
                    models.CharField(
                        help_text="An identifier used by GREGoR research centers to identify a set of participants for their internal tracking",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PmidId",
            fields=[
                (
                    "pmid_id",
                    models.CharField(
                        help_text="Publication which included participant; Used for publications which include participant known prior to or after inclusion in GREGoR",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportedRace",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TwinId",
            fields=[
                (
                    "twin_id",
                    models.CharField(
                        help_text="may be monozygotic, dizygotic, or polyzygotic",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
