# Generated by Django 5.0.1 on 2024-08-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalProjectId",
            fields=[
                (
                    "internal_project_id",
                    models.CharField(
                        help_text="An identifier used by GREGoR research centers to identify a set of participants for their internal tracking",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PmidId",
            fields=[
                (
                    "pmid_id",
                    models.CharField(
                        help_text="Publication which included participant; Used for publications which include participant known prior to or after inclusion in GREGoR",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportedRace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
