# Generated by Django 5.0.1 on 2025-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalProjectId",
            fields=[
                (
                    "internal_project_id",
                    models.CharField(
                        help_text="An identifier used by GREGoR research centers to identify a set of participants for their internal tracking",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PmidId",
            fields=[
                (
                    "pmid_id",
                    models.CharField(
                        help_text="Publication which included participant; Used for publications which include participant known prior to or after inclusion in GREGoR",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportedRace",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
