# Generated by Django 5.0.1 on 2025-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submodels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildAnalytes",
            fields=[
                (
                    "child_analytes",
                    models.CharField(
                        help_text="List of downstream analyte IDs created from a biosample.",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
