# Generated by Django 5.2.3 on 2025-07-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submodels", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlignedId",
        ),
        migrations.DeleteModel(
            name="ExperimentId",
        ),
    ]
