# Generated by Django 5.0.1 on 2025-04-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0005_alter_biobank_child_analytes"),
        ("submodels", "0002_childanalytes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChildAnalytes",
        ),
    ]
