"""
Django settings for client project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

import os
import configparser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Reading and populating secrets and instance specific information
secrets = configparser.ConfigParser()

# Try reading `.secrets`, fallback to environment variables
secrets_file_path = os.path.join(BASE_DIR, ".secrets")

if os.path.exists(secrets_file_path):
    secrets.read(secrets_file_path)

# Handle missing GENEYX settings gracefully
GENEYX_APIDB = secrets.get("GENEYX", "GENEYX_APIDB", fallback="locahttps://analysis.geneyx.com/api")
GENEYX_CONTENT_TYPE = secrets.get("GENEYX", "GENEYX_CONTENT_TYPE", fallback="application/json")
GENEYX_PAGE_SIZE = secrets.getint("GENEYX", "GENEYX_PAGE_SIZE", fallback=2000)
GENEYX_USER_ID = secrets.get("GENEYX", "GENEYX_USER_ID", fallback="OOPS")
GENEYX_USER_KEY = secrets.get("GENEYX", "GENEYX_USER_KEY", fallback="OOPS")
