# Generated by Django 5.0.1 on 2026-07-08 00:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnvilUpload",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "upload_id",
                    models.CharField(
                        help_text="Immutable human-readable upload identifier, for example 'UCI_GREGoR_test_upload_v1'.",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("validation_failed", "Validation failed"),
                            ("ready_for_review", "Ready for review"),
                            ("approved", "Approved"),
                            ("exported", "Exported"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current Dashboard lifecycle state for this upload.",
                        max_length=30,
                    ),
                ),
                (
                    "gregor_model_version",
                    models.CharField(
                        default="1.12",
                        help_text="Canonical GREGoR data-model version used when validating and exporting this upload.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional upload-level notes for review or handoff.",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnVIL upload",
                "verbose_name_plural": "AnVIL uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnvilUploadTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "table_name",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical GREGoR table name, such as participant, experiment, aligned, or called_variants_dna_short_read.",
                        max_length=100,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of exported rows in this upload table.",
                    ),
                ),
                (
                    "column_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of columns written to the exported TSV. This preserves the exact generated table shape.",
                    ),
                ),
                (
                    "source_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="upload-builder summary of source models, source counts, filters, or other non-authoritative provenance details.",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Most recent table-generation error, if generation failed.",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_tables",
                        to="anvil.anvilupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnVIL upload table",
                "verbose_name_plural": "AnVIL upload tables",
                "ordering": ["table_name"],
            },
        ),
        migrations.CreateModel(
            name="AnvilUploadArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("table_tsv", "Table TSV"),
                            ("upload_manifest", "Upload manifest"),
                            ("wdl_inputs", "Validation WDL inputs"),
                            ("validation_report", "Validation report"),
                            ("readme", "README"),
                            ("package_archive", "Package archive"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text="Path inside the generated upload package, such as tables/participant.tsv or validation/report.json.",
                        max_length=500,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="File name only, retained for convenient listing and display.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME content type, such as text/tab-separated-values.",
                        max_length=100,
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Generated file size in bytes.", null=True
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 digest of the generated artifact.",
                        max_length=64,
                    ),
                ),
                (
                    "storage_uri",
                    models.CharField(
                        blank=True,
                        help_text="Optional storage location. Initially this may be a local package path; later it may hold a gs:// URI after staging.",
                        max_length=1000,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional artifact metadata, such as source table, expected MD5, or package-generation details.",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Most recent artifact-generation error, if generation failed.",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="anvil.anvilupload",
                    ),
                ),
                (
                    "upload_table",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated upload table for table-specific artifacts. Blank for upload-wide artifacts such as manifests and reports.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="anvil.anviluploadtable",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnVIL upload artifact",
                "verbose_name_plural": "AnVIL upload artifacts",
                "ordering": ["relative_path"],
            },
        ),
        migrations.CreateModel(
            name="AnvilUploadValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "validator_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard upload validator"),
                            ("local", "Local AnVIL intake harness"),
                            ("anvil", "AnVIL validate_gregor_model workflow"),
                        ],
                        db_index=True,
                        default="dashboard",
                        max_length=20,
                    ),
                ),
                (
                    "validator_version",
                    models.CharField(
                        blank=True,
                        help_text="Validator implementation/version, such as dashboard-0.1, local-harness-0.1, or a Dockstore workflow version.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Machine-readable validation summary, including table counts, error categories, and validator output metadata.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable validation outcome or failure summary.",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "report_artifact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional generated report artifact for this validation run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_reports",
                        to="anvil.anviluploadartifact",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="anvil.anvilupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnVIL upload validation run",
                "verbose_name_plural": "AnVIL upload validation runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAnvilUpload",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "upload_id",
                    models.CharField(
                        db_index=True,
                        help_text="Immutable human-readable upload identifier, for example 'UCI_GREGoR_test_upload_v1'.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("validation_failed", "Validation failed"),
                            ("ready_for_review", "Ready for review"),
                            ("approved", "Approved"),
                            ("exported", "Exported"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current Dashboard lifecycle state for this upload.",
                        max_length=30,
                    ),
                ),
                (
                    "gregor_model_version",
                    models.CharField(
                        default="1.12",
                        help_text="Canonical GREGoR data-model version used when validating and exporting this upload.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional upload-level notes for review or handoff.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AnVIL upload",
                "verbose_name_plural": "historical AnVIL uploads",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAnvilUploadArtifact",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("table_tsv", "Table TSV"),
                            ("upload_manifest", "Upload manifest"),
                            ("wdl_inputs", "Validation WDL inputs"),
                            ("validation_report", "Validation report"),
                            ("readme", "README"),
                            ("package_archive", "Package archive"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text="Path inside the generated upload package, such as tables/participant.tsv or validation/report.json.",
                        max_length=500,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="File name only, retained for convenient listing and display.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME content type, such as text/tab-separated-values.",
                        max_length=100,
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Generated file size in bytes.", null=True
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 digest of the generated artifact.",
                        max_length=64,
                    ),
                ),
                (
                    "storage_uri",
                    models.CharField(
                        blank=True,
                        help_text="Optional storage location. Initially this may be a local package path; later it may hold a gs:// URI after staging.",
                        max_length=1000,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional artifact metadata, such as source table, expected MD5, or package-generation details.",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Most recent artifact-generation error, if generation failed.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="anvil.anvilupload",
                    ),
                ),
                (
                    "upload_table",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Associated upload table for table-specific artifacts. Blank for upload-wide artifacts such as manifests and reports.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="anvil.anviluploadtable",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AnVIL upload artifact",
                "verbose_name_plural": "historical AnVIL upload artifacts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAnvilUploadTable",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "table_name",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical GREGoR table name, such as participant, experiment, aligned, or called_variants_dna_short_read.",
                        max_length=100,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of exported rows in this upload table.",
                    ),
                ),
                (
                    "column_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of columns written to the exported TSV. This preserves the exact generated table shape.",
                    ),
                ),
                (
                    "source_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="upload-builder summary of source models, source counts, filters, or other non-authoritative provenance details.",
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Most recent table-generation error, if generation failed.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="anvil.anvilupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AnVIL upload table",
                "verbose_name_plural": "historical AnVIL upload tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAnvilUploadValidationRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "validator_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard upload validator"),
                            ("local", "Local AnVIL intake harness"),
                            ("anvil", "AnVIL validate_gregor_model workflow"),
                        ],
                        db_index=True,
                        default="dashboard",
                        max_length=20,
                    ),
                ),
                (
                    "validator_version",
                    models.CharField(
                        blank=True,
                        help_text="Validator implementation/version, such as dashboard-0.1, local-harness-0.1, or a Dockstore workflow version.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Machine-readable validation summary, including table counts, error categories, and validator output metadata.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable validation outcome or failure summary.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_artifact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional generated report artifact for this validation run.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="anvil.anviluploadartifact",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="anvil.anvilupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AnVIL upload validation run",
                "verbose_name_plural": "historical AnVIL upload validation runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="anviluploadtable",
            constraint=models.UniqueConstraint(
                fields=("upload", "table_name"), name="anvil_upload_unique_table_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="anviluploadartifact",
            constraint=models.UniqueConstraint(
                fields=("upload", "relative_path"),
                name="anvil_upload_unique_artifact_path",
            ),
        ),
    ]
