# Generated by Django 5.0.1 on 2025-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submodels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignedId",
            fields=[
                (
                    "aligned_id",
                    models.CharField(
                        help_text="From aligned table. Includes sr-gs, pacbio, nanopore, etc. alignments",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentId",
            fields=[
                (
                    "experiment_id",
                    models.CharField(
                        help_text="From experiments table. Includes sr-gs, pacbio, nanopore, etc. experiments",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
