# Generated by Django 5.0.1 on 2025-10-20 13:28

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HPOTerm",
            fields=[
                (
                    "hpo_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("label", models.TextField()),
                ("definition", models.TextField(blank=True, null=True)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("release", models.CharField(max_length=32)),
                ("deprecated", models.BooleanField(default=False)),
                ("label_normalized", models.TextField(db_index=True)),
                ("synonyms_concat", models.TextField(blank=True)),
                (
                    "search_tsv",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HPOArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("source_url", models.TextField()),
                ("csv_path", models.TextField()),
                ("faiss_path", models.TextField()),
                ("npz_path", models.TextField()),
                ("embed_model", models.CharField(max_length=128)),
                ("csv_sha256", models.CharField(max_length=128)),
                ("built_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active"], name="hpo_hpoarti_active_a719f2_idx"
                    ),
                    models.Index(
                        fields=["release"], name="hpo_hpoarti_release_d0b101_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HPOEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="hpo.hpoterm",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="hpo.hpoterm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent"], name="hpo_hpoedge_parent__b12b02_idx"
                    ),
                    models.Index(
                        fields=["child"], name="hpo_hpoedge_child_i_9f6afc_idx"
                    ),
                ],
                "unique_together": {("parent", "child")},
            },
        ),
    ]
