# Generated by Django 5.0.1 on 2025-10-20 13:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hpo", "0002_enable_extensions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hpoterm",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_tsv"], name="hpo_term_tsv_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="hpoterm",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["label_normalized"],
                name="hpo_term_trgm_label",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="hpoterm",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["synonyms_concat"],
                name="hpo_term_trgm_syn",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
