# Generated by Django 5.0.1 on 2024-05-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InternalProjectId',
            fields=[
                ('internal_project_id', models.CharField(help_text='An identifier used by GREGoR research centers to identify a set of participants for their internal tracking', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhenotypeDescription',
            fields=[
                ('phenotype_description', models.CharField(help_text="For unaffected/relatives, can note 'parent of ...' or 'relative of ...'", max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PmidId',
            fields=[
                ('pmid_id', models.CharField(help_text='Publication which included participant; Used for publications which include participant known prior to or after inclusion in GREGoR', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwinId',
            fields=[
                ('twin_id', models.CharField(help_text='may be monozygotic, dizygotic, or polyzygotic', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.CharField(help_text='Subject/Participant Identifier (primary key) Example values: BCM_Subject_1, BROAD_subj89054.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('gregor_center', models.CharField(blank=True, choices=[('BCM', 'Baylor College of Medicine Research Center'), ('BROAD', 'Broad Institute'), ('CNH_I', "Children's National Hospital"), ('UW_CRDR', 'University of Washington Center for Rare Disease Research'), ('GSS', 'GREGoR Stanford Site'), ('UW_DCC', 'University of Washington’s School of Public Health')], default=None, help_text='GREGoR Center to which the participant is originally associated', max_length=255)),
                ('consent_code', models.CharField(choices=[('GRU', 'GRU'), ('HMB', 'HMB')], help_text="Consent group pertaining to this participant's data", max_length=255)),
                ('recontactable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Is the originating GREGoR Center likely able to recontact this participant', max_length=255)),
                ('prior_testing', models.TextField(blank=True, help_text='Text description of any genetic testing for individual conducted prior to enrollment')),
                ('paternal_id', models.CharField(default='0', help_text='participant_id for father; 0 if not available', max_length=255)),
                ('maternal_id', models.CharField(default='0', help_text='participant_id for mother; 0 if not available', max_length=255)),
                ('proband_relationship', models.CharField(choices=[('Self', 'SELF'), ('Mother', 'MOTHER'), ('Father', 'FATHER'), ('Sibling', 'SIBLING'), ('Child', 'CHILD'), ('Maternal Half Sibling', 'MATERNAL_HALF_SIBLING'), ('Paternal Half Sibling', 'PATERNAL_HALF_SIBLING'), ('Maternal Grandmother', 'MATERNAL_GRANDMOTHER'), ('Maternal Grandfather', 'MATERNAL_GRANDFATHER'), ('Paternal Grandmother', 'PATERNAL_GRANDMOTHER'), ('Paternal Grandfather', 'PATERNAL_GRANDFATHER'), ('Maternal Aunt', 'MATERNAL_AUNT'), ('Maternal Uncle', 'MATERNAL_UNCLE'), ('Paternal Aunt', 'PATERNAL_AUNT'), ('Paternal Uncle', 'PATERNAL_UNCLE'), ('Niece', 'NIECE'), ('Nephew', 'NEPHEW'), ('Maternal 1st Cousin', 'MATERNAL_FIRST_COUSIN'), ('Paternal 1st Cousin', 'PATERNAL_FIRST_COUSIN'), ('Other', 'OTHER'), ('Unknown', 'UNKNOWN')], default='Unknown', help_text='Text description of individual relationship to proband in family, especially useful to capture relationships when connecting distant relatives and connecting relatives not studied', max_length=255)),
                ('proband_relationship_detail', models.TextField(blank=True, help_text='Other proband relationship not captured in enumeration above')),
                ('sex', models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE'), ('Unknown', 'UNKNOWN')], default='Unknown', help_text='Biological sex assigned at birth (aligned with All of Us). If individual has a known DSD / not expected sex chromosome karyotype, this can be noted in the phenotype information section.', max_length=255)),
                ('sex_detail', models.TextField(blank=True, help_text="Optional free-text field to describe known discrepancies between 'sex' value (female=>XX, male=>XY) and actual sex chromosome karyotype")),
                ('reported_race', models.CharField(blank=True, help_text='Self/submitter-reported race (OMB categories', max_length=255)),
                ('reported_ethnicity', models.CharField(blank=True, choices=[('Hispanic or Latino', 'HISPANIC'), ('Not Hispanic or Latino', 'NON_HISPANIC')], default=None, help_text='Self/submitter-reported ethnicity (OMB categories)', max_length=255)),
                ('ancestry_detail', models.CharField(blank=True, help_text='Additional specific ancestry description free text beyond what is captured by OMB race/ethnicity categories', max_length=255)),
                ('age_at_last_observation', models.CharField(blank=True, help_text='Age at last observation, aka age in years at the last time the center can vouch for the accuracy phenotype data. For conditions with later age of onset, this field lets users know if individuals marked as unaffected were younger or older than the age when the phenotype is expected to appear', max_length=255)),
                ('affected_status', models.TextField(blank=True, help_text='Indicate affected status of individual (overall with respect to primary phenotype in the family). Note: Affected participants must have entry in phenotype table.')),
                ('phenotype_description', models.TextField(blank=True, help_text="human-readable 'Phenotypic one-line summary' for why this individual is of interest. Could be the same as the term_details value in the Phenotype table. Strongly encourage/required for proband.")),
                ('age_at_enrollment', models.CharField(blank=True, help_text='age in years at which consent was originally obtained', max_length=255)),
                ('solve_status', models.CharField(help_text="Indication of whether the submitting RC considers this case 'solved'", max_length=255)),
                ('missing_variant_case', models.TextField(blank=True, help_text='Indication of whether this is known to be a missing variant case, see notes for a description of the Missing Variant Project and inclusion criteria.')),
                ('missing_variant_details', models.TextField(blank=True, help_text='For missing variant cases, indicate gene(s) or region of interest and reason for inclusion in MVP')),
                ('family_id', models.OneToOneField(blank=True, help_text='Identifier for family', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.family')),
                ('internal_project_id', models.ManyToManyField(blank=True, help_text='An identifier used by GREGoR research centers to identifya set of participants for their internal tracking', related_name='participant', to='metadata.internalprojectid')),
                ('pmid_id', models.ManyToManyField(blank=True, help_text='Case specific PubMed ID if applicable', related_name='participant', to='metadata.pmidid')),
                ('twin_id', models.ManyToManyField(blank=True, help_text='participant_id for twins, triplets, etc; 0 if not available', related_name='participant', to='metadata.twinid')),
            ],
        ),
    ]
