# Generated by Django 5.0.1 on 2024-07-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "family_id",
                    models.CharField(
                        help_text="Identifier for family (primary key). Needs to be Unique across centers, use participant.gregor_center as ID prefix.",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consanguinity",
                    models.CharField(
                        choices=[
                            ("None suspected", "None suspected"),
                            ("Suspected", "Suspected"),
                            ("Present", "Present"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        help_text="Indicate if consanguinity is present or suspected within a family",
                        max_length=50,
                    ),
                ),
                (
                    "consanguinity_detail",
                    models.TextField(
                        blank=True,
                        help_text="Free text description of any additional consanguinity details",
                    ),
                ),
                (
                    "pedigree_file",
                    models.CharField(
                        blank=True,
                        help_text="Name of file (renamed from pedigree_image because it can contain a PED file or image)",
                        max_length=255,
                    ),
                ),
                (
                    "pedigree_file_detail",
                    models.TextField(
                        blank=True,
                        help_text="Free text description of other family structure/pedigree file caption or legend.",
                    ),
                ),
                (
                    "family_history_detail",
                    models.TextField(
                        blank=True,
                        help_text="Details about family history that do not fit into structured fields. Family relationship terms should be relative to the proband.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalProjectId",
            fields=[
                (
                    "internal_project_id",
                    models.CharField(
                        help_text="An identifier used by GREGoR research centers to identify a set of participants for their internal tracking",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhenotypeDescription",
            fields=[
                (
                    "phenotype_description",
                    models.CharField(
                        help_text="For unaffected/relatives, can note 'parent of ...' or 'relative of ...'",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PmidId",
            fields=[
                (
                    "pmid_id",
                    models.CharField(
                        help_text="Publication which included participant; Used for publications which include participant known prior to or after inclusion in GREGoR",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TwinId",
            fields=[
                (
                    "twin_id",
                    models.CharField(
                        help_text="may be monozygotic, dizygotic, or polyzygotic",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "participant_id",
                    models.CharField(
                        help_text="Subject/Participant Identifier (primary key)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "gregor_center",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BCM", "Baylor College of Medicine Research Center"),
                            ("BROAD", "Broad Institute"),
                            ("CNH_I", "Children's National Hospital"),
                            ("UCI", "University of California Irvine"),
                            (
                                "UW_CRDR",
                                "University of Washington Center for Rare Disease Research",
                            ),
                            ("GSS", "GREGoR Stanford Site"),
                            (
                                "UW_DCC",
                                "University of Washington’s School of Public Health",
                            ),
                        ],
                        default=None,
                        help_text="GREGoR Center to which the participant is originally associated",
                        max_length=255,
                    ),
                ),
                (
                    "consent_code",
                    models.CharField(
                        choices=[("GRU", "GRU"), ("HMB", "HMB")],
                        help_text="Consent group pertaining to this participant's data",
                        max_length=255,
                    ),
                ),
                (
                    "recontactable",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        help_text="Is the originating GREGoR Center likely able to recontact this participant",
                        max_length=255,
                    ),
                ),
                (
                    "prior_testing",
                    models.TextField(
                        blank=True,
                        help_text="Text description of any genetic testing for individual conducted prior to enrollment",
                    ),
                ),
                (
                    "paternal_id",
                    models.CharField(
                        default="0",
                        help_text="participant_id for father; 0 if not available",
                        max_length=255,
                    ),
                ),
                (
                    "maternal_id",
                    models.CharField(
                        default="0",
                        help_text="participant_id for mother; 0 if not available",
                        max_length=255,
                    ),
                ),
                (
                    "proband_relationship",
                    models.CharField(
                        choices=[
                            ("Self", "SELF"),
                            ("Mother", "MOTHER"),
                            ("Father", "FATHER"),
                            ("Sibling", "SIBLING"),
                            ("Child", "CHILD"),
                            ("Maternal Half Sibling", "MATERNAL_HALF_SIBLING"),
                            ("Paternal Half Sibling", "PATERNAL_HALF_SIBLING"),
                            ("Maternal Grandmother", "MATERNAL_GRANDMOTHER"),
                            ("Maternal Grandfather", "MATERNAL_GRANDFATHER"),
                            ("Paternal Grandmother", "PATERNAL_GRANDMOTHER"),
                            ("Paternal Grandfather", "PATERNAL_GRANDFATHER"),
                            ("Maternal Aunt", "MATERNAL_AUNT"),
                            ("Maternal Uncle", "MATERNAL_UNCLE"),
                            ("Paternal Aunt", "PATERNAL_AUNT"),
                            ("Paternal Uncle", "PATERNAL_UNCLE"),
                            ("Niece", "NIECE"),
                            ("Nephew", "NEPHEW"),
                            ("Maternal 1st Cousin", "MATERNAL_FIRST_COUSIN"),
                            ("Paternal 1st Cousin", "PATERNAL_FIRST_COUSIN"),
                            ("Other", "OTHER"),
                            ("Unknown", "UNKNOWN"),
                        ],
                        default="Unknown",
                        help_text="Text description of individual relationship to proband in family, especially useful to capture relationships when connecting distant relatives and connecting relatives not studied",
                        max_length=255,
                    ),
                ),
                (
                    "proband_relationship_detail",
                    models.TextField(
                        blank=True,
                        help_text="Other proband relationship not captured in enumeration above",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Female", "FEMALE"),
                            ("Male", "MALE"),
                            ("Unknown", "UNKNOWN"),
                        ],
                        default="Unknown",
                        help_text="Biological sex assigned at birth (aligned with All of Us). If individual has a known DSD / not expected sex chromosome karyotype, this can be noted in the phenotype information section.",
                        max_length=255,
                    ),
                ),
                (
                    "sex_detail",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text field to describe known discrepancies between 'sex' value (female=>XX, male=>XY) and actual sex chromosome karyotype",
                    ),
                ),
                (
                    "reported_race",
                    models.CharField(
                        blank=True,
                        help_text="Self/submitter-reported race (OMB categories",
                        max_length=255,
                    ),
                ),
                (
                    "reported_ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Hispanic or Latino", "HISPANIC"),
                            ("Not Hispanic or Latino", "NON_HISPANIC"),
                        ],
                        help_text="Self/submitter-reported ethnicity (OMB categories)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ancestry_detail",
                    models.CharField(
                        blank=True,
                        help_text="Additional specific ancestry description free text beyond what is captured by OMB race/ethnicity categories",
                        max_length=255,
                    ),
                ),
                (
                    "age_at_last_observation",
                    models.FloatField(
                        blank=True,
                        help_text="Age at last observation, aka age in years at the last time the center can vouch for the accuracy phenotype data. For conditions with later age of onset, this field lets users know if individuals marked as unaffected were younger or older than the age when the phenotype is expected to appear",
                        null=True,
                    ),
                ),
                (
                    "affected_status",
                    models.TextField(
                        blank=True,
                        help_text="Indicate affected status of individual (overall with respect to primary phenotype in the family). Note: Affected participants must have entry in phenotype table.",
                    ),
                ),
                (
                    "phenotype_description",
                    models.TextField(
                        blank=True,
                        help_text="human-readable 'Phenotypic one-line summary' for why this individual is of interest. Could be the same as the term_details value in the Phenotype table. Strongly encourage/required for proband.",
                    ),
                ),
                (
                    "age_at_enrollment",
                    models.FloatField(
                        blank=True,
                        help_text="age in years at which consent was originally obtained",
                        null=True,
                    ),
                ),
                (
                    "solve_status",
                    models.CharField(
                        help_text="Indication of whether the submitting RC considers this case 'solved'",
                        max_length=255,
                    ),
                ),
                (
                    "missing_variant_case",
                    models.TextField(
                        blank=True,
                        help_text="Indication of whether this is known to be a missing variant case, see notes for a description of the Missing Variant Project and inclusion criteria.",
                    ),
                ),
                (
                    "missing_variant_details",
                    models.TextField(
                        blank=True,
                        help_text="For missing variant cases, indicate gene(s) or region of interest and reason for inclusion in MVP",
                    ),
                ),
                (
                    "family_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Identifier for family",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metadata.family",
                    ),
                ),
                (
                    "internal_project_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="An identifier used by GREGoR research centers to identifya set of participants for their internal tracking",
                        related_name="participants",
                        to="metadata.internalprojectid",
                    ),
                ),
                (
                    "pmid_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Case specific PubMed ID if applicable",
                        related_name="participants",
                        to="metadata.pmidid",
                    ),
                ),
                (
                    "twin_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="participant_id for twins, triplets, etc; 0 if not available",
                        related_name="participants",
                        to="metadata.twinid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analyte",
            fields=[
                (
                    "analyte_id",
                    models.CharField(
                        help_text="Identifier for an analyte from a primary biosample source",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analyte_type",
                    models.CharField(
                        choices=[
                            ("DNA", "DNA"),
                            ("RNA", "RNA"),
                            ("cDNA", "cDNA"),
                            ("blood plasma", "blood plasma"),
                            ("frozen whole blood", "frozen whole blood"),
                            ("high molecular weight DNA", "high molecular weight DNA"),
                            ("urine", "urine"),
                        ],
                        help_text="Analyte derived from the primary biosample. The actual thing you're sticking into a machine to analyze/sequence",
                        max_length=50,
                    ),
                ),
                (
                    "analyte_processing_details",
                    models.TextField(
                        blank=True,
                        help_text="Details about how the analyte or original biosample was extracted or processed",
                        null=True,
                    ),
                ),
                (
                    "primary_biosample",
                    models.CharField(
                        choices=[
                            ("UBERON:0000479", "tissue"),
                            ("UBERON:0003714", "neural tissue"),
                            ("UBERON:0001836", "saliva"),
                            ("UBERON:0001003", "skin epidermis"),
                            ("UBERON:0002385", "muscle tissue"),
                            ("UBERON:0000178", "whole blood"),
                            ("UBERON:0002371", "bone marrow"),
                            ("UBERON:0006956", "buccal mucosa"),
                            ("UBERON:0001359", "cerebrospinal fluid"),
                            ("UBERON:0001088", "urine"),
                            ("UBERON:0019306", "nose epithelium"),
                            ("CL:0000034", "iPSC"),
                            ("CL:0000576", "monocytes - PBMCs"),
                            ("CL:0000542", "lymphocytes - LCLs"),
                            ("CL:0000057", "fibroblasts"),
                            ("UBERON:0005291", "embryonic tissue"),
                            ("CL:0011020", "iPSC NPC"),
                            ("UBERON:0002037", "cerebellum tissue"),
                            ("UBERON:0001133", "cardiac tissue"),
                        ],
                        help_text="Tissue type of biosample taken from the participant that the analyte was extracted or processed from",
                        max_length=100,
                    ),
                ),
                (
                    "primary_biosample_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional ID for the biosample; allows for linking of multiple analytes extracted or processed from the same biosample",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "primary_biosample_details",
                    models.TextField(
                        blank=True,
                        help_text="Free text to capture information not in structured fields",
                        null=True,
                    ),
                ),
                (
                    "tissue_affected_status",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default=False,
                        help_text="If applicable to disease (suspected mosaic), indicates if the tissue is from an affected source.",
                        max_length=50,
                    ),
                ),
                (
                    "age_at_collection",
                    models.FloatField(
                        blank=True,
                        help_text="Age of participant in years at biosample collection",
                        null=True,
                    ),
                ),
                (
                    "participant_drugs_intake",
                    models.TextField(
                        blank=True,
                        help_text="The list of drugs patient is on, at the time of sample collection. Helpful during analysis of metabolomics and immune assays",
                        null=True,
                    ),
                ),
                (
                    "participant_special_diet",
                    models.TextField(
                        blank=True,
                        help_text="If the patient was fasting, when the sample was collected. Relevant when analyzing metabolomics data",
                        null=True,
                    ),
                ),
                (
                    "hours_since_last_meal",
                    models.FloatField(
                        blank=True,
                        help_text="Hours since last meal, relevant when analyzing metabolomics data",
                        null=True,
                    ),
                ),
                (
                    "passage_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Passage number is relevant for fibroblast cultures and possibly iPSC.",
                        null=True,
                    ),
                ),
                (
                    "time_to_freeze",
                    models.FloatField(
                        blank=True,
                        help_text="Time (in hours) from collection to freezing the sample. Delayed freeze turns out to be useful / important info for PaxGene blood (for RNA isolation).",
                        null=True,
                    ),
                ),
                (
                    "sample_transformation_detail",
                    models.TextField(
                        blank=True,
                        help_text="Details regarding sample transformation",
                        null=True,
                    ),
                ),
                (
                    "quality_issues",
                    models.TextField(
                        blank=True,
                        help_text="Freetext (limited characters) to concisely describe if there are any QC issues that would be important to note",
                        null=True,
                    ),
                ),
                (
                    "participant_id",
                    models.ForeignKey(
                        db_column="participant_id",
                        help_text="The participant from whom the biosample was taken",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytes",
                        to="metadata.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phenotype",
            fields=[
                (
                    "phenotype_id",
                    models.CharField(
                        help_text="Unique identifier for the phenotype entry. This ID generated when loading into AnVIL data table and is not included in the uploaded .tsv file",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term_id",
                    models.CharField(
                        help_text="Identifier for the term within the ontology",
                        max_length=255,
                    ),
                ),
                (
                    "presence",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Indicates if the phenotype is present, absent, or unknown.",
                        max_length=100,
                    ),
                ),
                (
                    "ontology",
                    models.CharField(
                        choices=[
                            ("HPO", "Human Phenotype Ontology"),
                            ("MONDO", "Mondo Disease Ontology"),
                            ("OMIM", "Online Mendelian Inheritance in Man"),
                            ("ORPHANET", "Orphanet"),
                            ("SNOMED", "Systematized Nomenclature of Medicine"),
                            ("ICD10", "International Classification of Diseases - 10"),
                        ],
                        default="hpo",
                        help_text="The ontology used to classify the phenotype term",
                        max_length=100,
                    ),
                ),
                (
                    "additional_details",
                    models.TextField(
                        blank=True,
                        help_text="modifier of a term where the additional details are not supported/available as a term in HPO",
                    ),
                ),
                (
                    "onset_age_range",
                    models.CharField(
                        choices=[
                            ("HP:0003581", "Neonatal"),
                            ("HP:0030674", "Infantile"),
                            ("HP:0011463", "Childhood"),
                            ("HP:0003577", "Adolescence"),
                            ("HP:0025708", "Adult"),
                            ("HP:0011460", "Old Age"),
                            ("HP:0011461", "Young Adult"),
                            ("HP:0003593", "Middle Age"),
                            ("HP:0025709", "Late Adult"),
                            ("HP:0003621", "All"),
                            ("HP:0034199", "Early Childhood"),
                            ("HP:0003584", "Late Childhood"),
                            ("HP:0025710", "Young Middle Age"),
                            ("HP:0003596", "Late Neonatal"),
                            ("HP:0003623", "Late"),
                            ("HP:0410280", "Early Neonatal"),
                            ("HP:4000040", "Late Infancy"),
                            ("HP:0034198", "Second Decade"),
                            ("HP:0034197", "Third Decade"),
                            ("HP:0011462", "First Decade"),
                        ],
                        default="unknown",
                        help_text="Age range at the onset of the phenotype",
                        max_length=100,
                    ),
                ),
                (
                    "additional_modifiers",
                    models.TextField(
                        blank=True,
                        help_text="Additional modifiers that further specify the phenotype",
                    ),
                ),
                (
                    "syndromic",
                    models.CharField(
                        choices=[("syndromic", "non-syndromic")],
                        default="non-syndromic",
                        help_text="Indicates if the phenotype is part of a syndromic condition",
                        max_length=50,
                    ),
                ),
                (
                    "participant_id",
                    models.ForeignKey(
                        db_column="participant_id",
                        help_text="Identifier for the participant associated with this phenotype.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phenotypes",
                        to="metadata.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneticFindings",
            fields=[
                (
                    "genetic_findings_id",
                    models.CharField(
                        help_text="Unique ID of this variant in this participant",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "experiment_id",
                    models.CharField(
                        help_text="The experiment table and experiment ID(s) in which discovery was identified",
                        max_length=255,
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("SNV", "Single Nucleotide Variant"),
                            ("INDEL", "Insertion/Deletion"),
                            ("SV", "Structural Variant"),
                            ("CNV", "Copy Number Variant"),
                            ("RE", "Repeat Expansion"),
                            ("MEI", "Mobile Element Insertion"),
                            ("STR", "Short Tandem Repeat"),
                        ],
                        help_text="Type of genetic variant",
                        max_length=50,
                    ),
                ),
                (
                    "sv_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of structural variant if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "variant_reference_assembly",
                    models.CharField(
                        help_text="The genome build for identifying the variant position",
                        max_length=50,
                    ),
                ),
                (
                    "chrom",
                    models.CharField(
                        help_text="Chromosome of the variant", max_length=10
                    ),
                ),
                (
                    "chrom_end",
                    models.CharField(
                        blank=True,
                        help_text="End position chromosome of SV",
                        max_length=10,
                    ),
                ),
                ("pos", models.IntegerField(help_text="Start position of the variant")),
                (
                    "pos_end",
                    models.IntegerField(
                        blank=True, help_text="End position of SV", null=True
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="Reference allele of the variant", max_length=255
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        help_text="Alternate allele of the variant", max_length=255
                    ),
                ),
                (
                    "copy_number",
                    models.IntegerField(
                        blank=True, help_text="CNV copy number", null=True
                    ),
                ),
                (
                    "ClinGen_allele_ID",
                    models.CharField(
                        blank=True,
                        help_text="ClinGen Allele ID for cross table reference",
                        max_length=255,
                    ),
                ),
                (
                    "gene_of_interest",
                    models.CharField(
                        help_text="HGNC approved symbol of the known or candidate gene(s)",
                        max_length=255,
                    ),
                ),
                (
                    "transcript",
                    models.CharField(
                        blank=True,
                        help_text="Text description of transcript overlapping the variant",
                        max_length=255,
                    ),
                ),
                (
                    "hgvsc",
                    models.CharField(
                        blank=True,
                        help_text="HGVS c. description of the variant",
                        max_length=255,
                    ),
                ),
                (
                    "hgvsp",
                    models.CharField(
                        blank=True,
                        help_text="HGVS p. description of the variant",
                        max_length=255,
                    ),
                ),
                (
                    "hgvs",
                    models.CharField(
                        blank=True,
                        help_text="Genomic HGVS description of the variant",
                        max_length=255,
                    ),
                ),
                (
                    "zygosity",
                    models.CharField(
                        choices=[
                            ("Homozygous", "Homozygous"),
                            ("Heterozygous", "Heterozygous"),
                            ("Hemizygous", "Hemizygous"),
                        ],
                        help_text="Zygosity of variant",
                        max_length=50,
                    ),
                ),
                (
                    "allele_balance_or_heteroplasmy_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Reported allele balance (mosaic) or heteroplasmy percentage (mitochondrial)",
                        null=True,
                    ),
                ),
                (
                    "variant_inheritance",
                    models.CharField(
                        choices=[
                            ("De Novo", "De Novo"),
                            ("Inherited", "Inherited"),
                            ("Unknown", "Unknown"),
                        ],
                        help_text="Detection of variant in parents",
                        max_length=50,
                    ),
                ),
                (
                    "linked_variant",
                    models.CharField(
                        blank=True,
                        help_text="Second variant in recessive cases",
                        max_length=255,
                    ),
                ),
                (
                    "linked_variant_phase",
                    models.CharField(
                        blank=True, help_text="Phase of linked variants", max_length=50
                    ),
                ),
                (
                    "gene_known_for_phenotype",
                    models.CharField(
                        blank=True,
                        help_text="Indicate if the gene listed is a candidate or known disease gene",
                        max_length=50,
                    ),
                ),
                (
                    "known_condition_name",
                    models.CharField(
                        blank=True,
                        help_text="Condition name consistent with the variant/phenotype/inheritance",
                        max_length=255,
                    ),
                ),
                (
                    "condition_id",
                    models.CharField(
                        blank=True,
                        help_text="MONDO/OMIM number for condition used for variant interpretation",
                        max_length=50,
                    ),
                ),
                (
                    "condition_inheritance",
                    models.CharField(
                        blank=True,
                        help_text="Expected inheritance of the condition used for variant interpretation",
                        max_length=50,
                    ),
                ),
                (
                    "GREGoR_variant_classification",
                    models.CharField(
                        blank=True,
                        help_text="Clinical significance of variant described to condition listed as determined by the RC's variant curation",
                        max_length=50,
                    ),
                ),
                (
                    "GREGoR_ClinVar_SCV",
                    models.CharField(
                        blank=True,
                        help_text="ClinVar accession number for the variant curation submitted by your center",
                        max_length=255,
                    ),
                ),
                (
                    "gene_disease_validity",
                    models.CharField(
                        choices=[("Valid", "Valid"), ("Invalid", "Invalid")],
                        help_text="Validity assessment of the gene-disease relationship",
                        max_length=50,
                    ),
                ),
                (
                    "public_database_other",
                    models.CharField(
                        blank=True,
                        help_text="Public databases that this variant in this participant has been submitted by the RC",
                        max_length=255,
                    ),
                ),
                (
                    "public_database_ID_other",
                    models.CharField(
                        blank=True,
                        help_text="Public database variant/case ID",
                        max_length=255,
                    ),
                ),
                (
                    "phenotype_contribution",
                    models.CharField(
                        blank=True,
                        help_text="Contribution of variant-linked condition to participant's phenotype",
                        max_length=50,
                    ),
                ),
                (
                    "method_of_discovery",
                    models.CharField(
                        choices=[
                            ("Sequencing", "Sequencing"),
                            ("GWAS", "Genome Wide Association Study"),
                        ],
                        help_text="The method/assay(s) used to identify the candidate",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free text field to explain edge cases or discovery updates or list parallel experiment IDs or list parental allele balance when mosaic... etc.",
                    ),
                ),
                (
                    "additional_family_members_with_variant",
                    models.ManyToManyField(
                        blank=True,
                        help_text="List of related participant IDs carrying the same variant",
                        related_name="family_variants",
                        to="metadata.participant",
                    ),
                ),
                (
                    "participant_id",
                    models.ForeignKey(
                        help_text="Subject/Participant Identifier within project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.participant",
                    ),
                ),
                (
                    "partial_contribution_explained",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific phenotypes explained by the condition associated with this variant/gene in cases of partial contribution",
                        to="metadata.phenotype",
                    ),
                ),
            ],
        ),
    ]
