# Generated by Django 5.2.3 on 2025-07-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biobank",
            options={
                "ordering": ["participant_id", "collection_date"],
                "verbose_name": "Biobank Sample (with traceability)",
            },
        ),
        migrations.RenameField(
            model_name="biobank",
            old_name="participant",
            new_name="participant_id",
        ),
        migrations.AlterField(
            model_name="biobank",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending shipment", "Pending shipment"),
                    ("Shipped", "Shipped"),
                    ("Received", "Received"),
                    ("Stored", "Stored"),
                    ("Extracted", "Extracted"),
                    ("QC issue", "QC issue, see comments"),
                    ("Data delivered", "Data delivered"),
                    ("Ready for variant analysis", "Ready for variant analysis"),
                    ("Lost", "Lost, see comments"),
                    ("Replacement requested", "Replacement requested"),
                ],
                help_text="Biospecimen status while ",
                max_length=100,
            ),
        ),
    ]
