# Generated by Django 5.0.1 on 2025-04-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experimentstage",
            old_name="alignments_list",
            new_name="alignments",
        ),
        migrations.RenameField(
            model_name="experimentstage",
            old_name="experiments_list",
            new_name="experiments",
        ),
    ]
