# Generated by Django 5.2.3 on 2025-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_alter_biobank_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneticfindings",
            name="variant_inheritance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("de novo", "De Novo"),
                    ("maternal", "Maternal"),
                    ("paternal", "Paternal"),
                    ("biparental", "Biparental"),
                    ("nonmaternal", "Nonmaternal"),
                    ("nonpaternal", "Nonpaternal"),
                    ("unknown", "Unknown"),
                ],
                help_text="Detection of variant in parents",
                max_length=50,
            ),
        ),
    ]
