# Generated by Django 5.0.1 on 2025-04-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_biobank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biobank",
            name="child_analytes",
            field=models.ForeignKey(
                blank=True,
                db_column="analyte_id",
                help_text="The analyte(s) derived from this biospecimen",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytes",
                to="metadata.analyte",
            ),
        ),
        migrations.AlterField(
            model_name="biobank",
            name="shipment_date",
            field=models.DateField(
                blank=True,
                help_text="If the status is shipped, then include a date when it was mailed out.",
                null=True,
            ),
        ),
    ]
