# Generated by Django 5.0.1 on 2026-02-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_alter_analyte_changed_by_alter_biobank_changed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneticfindings",
            name="method_of_discovery",
            field=models.JSONField(
                blank=True,
                choices=[
                    ("SR-ES", "Short Read Exome Sequencing"),
                    ("SR-GS", "Short Read Genome Sequencing"),
                    ("LR-GS", "Long Read Genome Sequencing"),
                    ("SNP array", "SNP Array"),
                    ("Optical mapping", "Optical Mapping"),
                    ("Karyotype", "Karyotype"),
                    ("SR RNA-seq", "Short Read RNA Sequencing"),
                    ("LR RNA-seq", "Long Read RNA Sequencing"),
                    ("SR-ES-reanalysis", "Short Read ES Reanalysis"),
                    ("SR-GS-reanalysis", "Short Read GS Reanalysis"),
                    ("LR-GS-reanalysis", "Long Read GS Reanalysis"),
                    ("SNP array-reanalysis", "SNP Array Reanalysis"),
                    ("Optical mapping-reanalysis", "Optical Mapping Reanalysis"),
                    ("Karyotype-reanalysis", "Karyotype Reanalysis"),
                    ("SR RNA-seq-reanalysis", "Short Read RNA-seq Reanalysis"),
                    ("LR RNA-seq-reanalysis", "Long Read RNA-seq Reanalysis"),
                    ("GENE PANEL", "Gene panel"),
                ],
                default=list,
                help_text="The method/assay(s) used to identify the candidate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneticfindings",
            name="method_of_discovery",
            field=models.JSONField(
                blank=True,
                choices=[
                    ("SR-ES", "Short Read Exome Sequencing"),
                    ("SR-GS", "Short Read Genome Sequencing"),
                    ("LR-GS", "Long Read Genome Sequencing"),
                    ("SNP array", "SNP Array"),
                    ("Optical mapping", "Optical Mapping"),
                    ("Karyotype", "Karyotype"),
                    ("SR RNA-seq", "Short Read RNA Sequencing"),
                    ("LR RNA-seq", "Long Read RNA Sequencing"),
                    ("SR-ES-reanalysis", "Short Read ES Reanalysis"),
                    ("SR-GS-reanalysis", "Short Read GS Reanalysis"),
                    ("LR-GS-reanalysis", "Long Read GS Reanalysis"),
                    ("SNP array-reanalysis", "SNP Array Reanalysis"),
                    ("Optical mapping-reanalysis", "Optical Mapping Reanalysis"),
                    ("Karyotype-reanalysis", "Karyotype Reanalysis"),
                    ("SR RNA-seq-reanalysis", "Short Read RNA-seq Reanalysis"),
                    ("LR RNA-seq-reanalysis", "Long Read RNA-seq Reanalysis"),
                    ("GENE PANEL", "Gene panel"),
                ],
                default=list,
                help_text="The method/assay(s) used to identify the candidate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalparticipant",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Female", "FEMALE"),
                    ("Male", "MALE"),
                    ("Unknown", "UNKNOWN"),
                ],
                default="Unknown",
                help_text="Biological sex assigned at birth (aligned with All of Us). If individual has a known DSD / not expected sex chromosome karyotype, this can be noted in the sex_detail field.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Female", "FEMALE"),
                    ("Male", "MALE"),
                    ("Unknown", "UNKNOWN"),
                ],
                default="Unknown",
                help_text="Biological sex assigned at birth (aligned with All of Us). If individual has a known DSD / not expected sex chromosome karyotype, this can be noted in the sex_detail field.",
                max_length=255,
            ),
        ),
    ]
