# Generated by Django 5.0.1 on 2026-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0003_alter_geneticfindings_method_of_discovery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biobank",
            name="box_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5x5 cryobox", "5x5 cryobox"),
                    ("7x7 cryobox", "7x7 cryobox"),
                    ("9x9 cryobox", "9x9 cryobox"),
                    ("10x10 cryobox", "10x10 cryobox"),
                    ("SBS plate", "SBS plate"),
                    ("Wire rack", "Wire rack"),
                    ("8x12 metal rack", "8x12 metal rack"),
                ],
                help_text="Box type the biospecimen is stored in",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbiobank",
            name="box_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5x5 cryobox", "5x5 cryobox"),
                    ("7x7 cryobox", "7x7 cryobox"),
                    ("9x9 cryobox", "9x9 cryobox"),
                    ("10x10 cryobox", "10x10 cryobox"),
                    ("SBS plate", "SBS plate"),
                    ("Wire rack", "Wire rack"),
                    ("8x12 metal rack", "8x12 metal rack"),
                ],
                help_text="Box type the biospecimen is stored in",
                max_length=50,
                null=True,
            ),
        ),
    ]
