# Generated by Django 5.0.1 on 2025-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0003_alter_biobank_child_analytes_and_more"),
        ("submodels", "0002_childanalytes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biobank",
            name="child_analytes",
        ),
        migrations.AddField(
            model_name="biobank",
            name="child_analytes",
            field=models.ManyToManyField(
                blank=True,
                help_text="The analyte(s) derived from this biospecimen",
                related_name="analytes",
                to="submodels.childanalytes",
            ),
        ),
    ]
