# Generated by Django 5.2.3 on 2025-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0003_alter_geneticfindings_variant_inheritance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneticfindings",
            name="alt",
            field=models.CharField(
                blank=True,
                help_text="Alternate allele of the variant",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="ref",
            field=models.CharField(
                blank=True,
                help_text="Reference allele of the variant",
                max_length=255,
                null=True,
            ),
        ),
    ]
