# Generated by Django 5.0.1 on 2025-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0004_alter_analyte_created_at_alter_analyte_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyte",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="biobank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
