# Generated by Django 5.2.3 on 2025-07-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0004_alter_geneticfindings_alt_alter_geneticfindings_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biobank",
            options={
                "ordering": ["participant_id", "collection_date"],
                "verbose_name": "Biobank Sample",
            },
        ),
    ]
