# Generated by Django 5.2.3 on 2025-08-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0005_alter_biobank_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biobank",
            options={
                "ordering": ["participant_id", "received_date"],
                "verbose_name": "Biobank Sample",
            },
        ),
        migrations.RenameField(
            model_name="biobank",
            old_name="collection_date",
            new_name="received_date",
        ),
        migrations.AlterField(
            model_name="analyte",
            name="participant_id",
            field=models.ForeignKey(
                db_column="participant_id",
                help_text="The participant from whom the biosample was taken",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytes",
                to="metadata.participant",
            ),
        ),
        migrations.AlterField(
            model_name="biobank",
            name="participant_id",
            field=models.ForeignKey(
                help_text="Participant associated with the sample",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="biobank_samples",
                to="metadata.participant",
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="participant_id",
            field=models.ForeignKey(
                help_text="Subject/Participant Identifier within project",
                on_delete=django.db.models.deletion.PROTECT,
                to="metadata.participant",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="family_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Identifier for family",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="metadata.family",
            ),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="participant_id",
            field=models.ForeignKey(
                db_column="participant_id",
                help_text="Identifier for the participant associated with this phenotype.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phenotypes",
                to="metadata.participant",
            ),
        ),
    ]
