# Generated by Django 5.0.1 on 2025-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0005_alter_biobank_child_analytes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biobank",
            name="child_analytes",
            field=models.ManyToManyField(
                blank=True,
                help_text="The analyte(s) derived from this biospecimen",
                related_name="analytes",
                to="metadata.analyte",
            ),
        ),
    ]
