# Generated by Django 5.0.1 on 2025-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0006_alter_biobank_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneticfindings",
            name="variant_type",
            field=models.JSONField(
                choices=[
                    ("SNV", "SNV: single nucelotide variants"),
                    ("INDEL", "INDEL: short insertion/deletions (<50bp)"),
                    ("SV", "SV: structural variants"),
                    ("RE", "RE: repeat elements"),
                    ("CNV", "CNV: copy number variants"),
                    ("MEI", "MEI: mobile element insertions"),
                    ("STR", "STR: short tandem repeats"),
                ],
                default=list,
                help_text="Type of genetic variant",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gregor_center",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BCM", "Baylor College of Medicine Research Center"),
                    ("BROAD", "Broad Institute"),
                    ("CNH_I", "Children's National Hospital"),
                    ("UCI", "University of California Irvine"),
                    (
                        "UW_CRDR",
                        "University of Washington Center for Rare Disease Research",
                    ),
                    ("GSS", "GREGoR Stanford Site"),
                    ("UW_DCC", "University of Washington’s School of Public Health"),
                    ("ILMN_IHOPE", "Illumina iHope Genetic Health Program"),
                ],
                default=None,
                help_text="GREGoR Center to which the participant is originally associated",
                max_length=255,
            ),
        ),
    ]
