# Generated by Django 5.0.1 on 2025-09-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0007_alter_geneticfindings_variant_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biobank",
            name="collection_source",
            field=models.CharField(
                blank=True,
                help_text="Name of institution who collected the biosample",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="GREGoR_variant_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Benign", "Benign"),
                    ("Likely benign", "Likely benign"),
                    ("Uncertain significance - low", "Uncertain significance - low"),
                    (
                        "Uncertain significance - moderate",
                        "Uncertain significance - moderate",
                    ),
                    ("Uncertain significance - high", "Uncertain significance - high"),
                    ("Uncertain significance", "Uncertain significance"),
                    ("Likely pathogenic", "Likely pathogenic"),
                    ("Pathogenic", "Pathogenic"),
                    ("Curation in progress", "Curation in progress"),
                    ("Well-established P/LP", "Well-established P/LP"),
                ],
                help_text="Clinical significance of variant described to condition listed as determined by the RC's variant curation. Currently optional; may be required if gene_known_for_phenotype = Known.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="gene_known_for_phenotype",
            field=models.CharField(
                blank=True,
                choices=[("Known", "Known"), ("Candidate", "Candidate")],
                help_text="Indicate if the gene listed is a candidate or known disease gene",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="method_of_discovery",
            field=models.JSONField(
                blank=True,
                choices=[
                    ("SR-ES", "Short Read Exome Sequencing"),
                    ("SR-GS", "Short Read Genome Sequencing"),
                    ("LR-GS", "Long Read Genome Sequencing"),
                    ("SNP array", "SNP Array"),
                    ("Optical mapping", "Optical Mapping"),
                    ("Karyotype", "Karyotype"),
                    ("SR RNA-seq", "Short Read RNA Sequencing"),
                    ("LR RNA-seq", "Long Read RNA Sequencing"),
                    ("SR-ES-reanalysis", "Short Read ES Reanalysis"),
                    ("SR-GS-reanalysis", "Short Read GS Reanalysis"),
                    ("LR-GS-reanalysis", "Long Read GS Reanalysis"),
                    ("SNP array-reanalysis", "SNP Array Reanalysis"),
                    ("Optical mapping-reanalysis", "Optical Mapping Reanalysis"),
                    ("Karyotype-reanalysis", "Karyotype Reanalysis"),
                    ("SR RNA-seq-reanalysis", "Short Read RNA-seq Reanalysis"),
                    ("LR RNA-seq-reanalysis", "Long Read RNA-seq Reanalysis"),
                ],
                default=list,
                help_text="The method/assay(s) used to identify the candidate",
            ),
        ),
        migrations.AlterField(
            model_name="geneticfindings",
            name="phenotype_contribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Partial", "Partial"),
                    ("Full", "Full"),
                    ("Uncertain", "Uncertain"),
                ],
                help_text="Contribution of variant-linked condition to participant's phenotype",
                max_length=50,
            ),
        ),
    ]
