name: Full CI (Django + React + Integration)

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Backend Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Django
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: "ci-temp-secret-key"
        run: |
          cd server
          mkdir -p staticfiles
          python manage.py migrate
          python manage.py collectstatic --noinput
          python manage.py runserver 0.0.0.0:8000 &

      - name: Run Django Tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: "ci-temp-secret-key"
        run: |
          cd server
          python manage.py test

  frontend-tests:
    name: React Tests
    runs-on: ubuntu-latest
    needs: backend-tests  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Run React Tests (Jest)
        env:
          REACT_APP_APIDB: "http://localhost:8000/"
        run: |
          cd client
          npm test -- --ci --watchAll=false
