name: Django CI

on: 
  push:
    branches:
      - dev  # Add other branches you want to test
  pull_request:
    branches:
      - dev

jobs:
  backend-tests:
    name: Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Set to your Python version

      - name: Install Backend Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Django
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: "ci-temp-secret-key"
        run: |
          cd server
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: "ci-temp-secret-key"
        run: |
          cd server
          python manage.py test

  frontend-tests:
    name: React Tests
    runs-on: ubuntu-latest
    needs: backend-tests 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v23.3.0

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Run React Tests (Jest)
        run: |
          cd client
          npm test -- --ci --watchAll=false